id: I1400086B
legacy_id: P009461
ocr_import_info:
  bdrc_scan_id: W1CZ1100
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T12:53:37'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:51:00.055819+00:00'
last_modified: 2022-08-31 02:53:38.459401
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1100
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1100
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཀླུ་སྒྲུབ་རྒྱ་མཚོ།
  author: མང་ཐོས་ཀླུ་སྒྲུབ་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.4585974537937884
  ocr_word_median_confidence_index: 0.44999998807907104
quality: null
bases:
  I1CZ1556:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1556
      total_pages: 1058
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1CZ1556.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.45869108276954884
    legacy_id: v002
  I1CZ1555:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1555
      total_pages: 1200
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1555.txt
    statistics:
      ocr_word_median_confidence_index: 0.44999998807907104
      ocr_word_mean_confidence_index: 0.45850509671732054
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
